### ISSUE TITLE
send digiline signal to only one port

### ISSUE THREAD

**Issue by DS-Minetest** [minetest-mods/digilines#37]
Would it be possible to give the ability to send a digiline signal to only one side?
eg. add an optional 3rd option to `digiline_send(channel,msg,port)` if no port is given then it sends to all else if it's `a`, `b`, `c` or `d` then only send in the direction
It would be really useful.

**Comment by DS-Minetest** [comment]
There are still no comments. :confused:

**Comment by electrodude** [comment]
`digiline_send(channel, msg)` is a Mesecons Luacontroller function.  Is that what you're talking about?  If so, it is not currently possible to do what you say, but it would be very easy to add.  Normally, though, you can just use different channels so you don't need to worry about sides.

The only use I really can see for this (other than for getting around poorly written mods) would be for making a digilines network switch to reduce congestion on large networks that branch at central points.  And side selection isn't even necessary for a switch - you could just use multiple luacontrollers.

**Comment by DS-Minetest** [comment]
I just don't want digiline event echo/duplication.

**Comment by Jeija** [comment]
> And side selection isn't even necessary for a switch - you could just use multiple luacontrollers.

I have to agree with this, so I'm not in favor of adding this functionality. The idea behind digilines is to abstract mesecons away from from the physical layout of the schematic to a system that is based on channels (so that code using digilines can be copied and pasted without caring about the physical location / surroundings of the luacontroller). Sending signals in only one direction doesn't really fit in that concept.

**Comment by numberZero** [comment]
Alternative suggestion: “hardware” digiline filter (that lets only certain channels pass) and diode (that lets the signal pass in one direction only). That would be way nicer and faster, both in terms of server load and digiline network bandwidth, than using multiple controllers.

**Comment by DS-Minetest** [comment]
@numberZero That would be good. If it's not wanted in digilines mod it could be done in a separate mod.

**Comment by numberZero** [comment]
@DS-Minetest https://github.com/numberZero/digiline_routing
* Diode works right now (no crafting yet). Note that it acts as a repeater rather than conventional wire so don’t short-circuit it or it will overheat.
* Filter is on my TODO list. It has to span 2 blocks to work with unmodified `digilines`.
* Splitter: the same.

**Comment by DS-Minetest** [comment]
@numberZero  Nice!
I'll close this issue.

**Comment by numberZero** [comment]
@DS-Minetest:
https://github.com/numberZero/digiline_routing/issues/1
https://github.com/numberZero/digiline_routing/issues/2
Feel free to add other device requests. I don’t want to overcomplicate this (that’s “hardware” processing, after all) but still there is a variety of possibilities.

**Comment by Emojigit** [comment]
Sending messages to multiple sides is terrifying. I am building a easy programable computer with luacontrollers and the messages goes to the wrong way causes security problem!

**Comment by numberZero** [comment]
New digiline hardware (obsoletes my `digiline_routing`): https://github.com/OgelGames/digicontrol
Warning: it patches `digilines`! (in runtime only ofc)

**Comment by Darin755** [comment]
So has this been implemented at all? If not, what part of the code would need to be modified to do this? I am not that well versed in Lua and the code base is fairly complex.

**Comment by Desour** [comment]
> So has this been implemented at all? If not, what part of the code would need to be modified to do this? I am not that well versed in Lua and the code base is fairly complex.

No. And it probably won't be implemented, see <https://github.com/minetest-mods/digilines/issues/37#issuecomment-270847381>.
