### ISSUE TITLE
LCD line length limits are not enforced properly

### ISSUE THREAD

**Issue by Hawk777** [minetest-mods/digilines#63]
Due to the test `string.len(line)+string.len(word) < LINE_LENGTH`, if the first word is more than *11* characters (not 12!) long, then the first line is actually rendered completely empty, with the first word pushed to the second line. Subsequent lines always consume at least one word, even if the words are very long, and are also able to properly display words up to 12 characters long.

**Comment by PeterNerlich** [comment]
This is fixed in my rework of the whole line breaking algorithm in #64.

**Comment by Hawk777** [comment]
Indeed it is, thank you.
